import { Deck } from '@/types';

export const seedDecks: Deck[] = [
  {
    id: 'animals-deck',
    title: 'Animals',
    description: 'Learn about different animals with pictures and names',
    category: 'animals',
    cardCount: 10,
    isFeatured: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    cards: [
      {
        id: 'animal-1',
        front: '🐶',
        back: 'Dog',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-2',
        front: '🐱',
        back: 'Cat',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-3',
        front: '🐘',
        back: 'Elephant',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-4',
        front: '🦁',
        back: 'Lion',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-5',
        front: '🐼',
        back: 'Panda',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-6',
        front: '🦊',
        back: 'Fox',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-7',
        front: '🐻',
        back: 'Bear',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-8',
        front: '🐯',
        back: 'Tiger',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-9',
        front: '🐸',
        back: 'Frog',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'animal-10',
        front: '🦋',
        back: 'Butterfly',
        learned: false,
        createdAt: Date.now(),
      },
    ],
  },
  {
    id: 'colors-deck',
    title: 'Colors',
    description: 'Learn basic colors with visual examples',
    category: 'colors',
    cardCount: 8,
    isFeatured: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    cards: [
      {
        id: 'color-1',
        front: '🔴',
        back: 'Red',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'color-2',
        front: '🔵',
        back: 'Blue',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'color-3',
        front: '🟢',
        back: 'Green',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'color-4',
        front: '🟡',
        back: 'Yellow',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'color-5',
        front: '🟠',
        back: 'Orange',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'color-6',
        front: '🟣',
        back: 'Purple',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'color-7',
        front: '⚫',
        back: 'Black',
        learned: false,
        createdAt: Date.now(),
      },
      {
        id: 'color-8',
        front: '⚪',
        back: 'White',
        learned: false,
        createdAt: Date.now(),
      },
    ],
  },
  {
    id: 'alphabet-deck',
    title: 'Alphabet',
    description: 'Learn the ABCs with examples from A to Z',
    category: 'alphabet',
    cardCount: 26,
    isFeatured: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    cards: [
      { id: 'alpha-1', front: 'A', back: 'A is for Apple 🍎', learned: false, createdAt: Date.now() },
      { id: 'alpha-2', front: 'B', back: 'B is for Ball ⚽', learned: false, createdAt: Date.now() },
      { id: 'alpha-3', front: 'C', back: 'C is for Cat 🐱', learned: false, createdAt: Date.now() },
      { id: 'alpha-4', front: 'D', back: 'D is for Dog 🐶', learned: false, createdAt: Date.now() },
      { id: 'alpha-5', front: 'E', back: 'E is for Elephant 🐘', learned: false, createdAt: Date.now() },
      { id: 'alpha-6', front: 'F', back: 'F is for Fish 🐟', learned: false, createdAt: Date.now() },
      { id: 'alpha-7', front: 'G', back: 'G is for Grapes 🍇', learned: false, createdAt: Date.now() },
      { id: 'alpha-8', front: 'H', back: 'H is for House 🏠', learned: false, createdAt: Date.now() },
      { id: 'alpha-9', front: 'I', back: 'I is for Ice Cream 🍦', learned: false, createdAt: Date.now() },
      { id: 'alpha-10', front: 'J', back: 'J is for Jellyfish 🪼', learned: false, createdAt: Date.now() },
      { id: 'alpha-11', front: 'K', back: 'K is for Kite 🪁', learned: false, createdAt: Date.now() },
      { id: 'alpha-12', front: 'L', back: 'L is for Lion 🦁', learned: false, createdAt: Date.now() },
      { id: 'alpha-13', front: 'M', back: 'M is for Moon 🌙', learned: false, createdAt: Date.now() },
      { id: 'alpha-14', front: 'N', back: 'N is for Nest 🪹', learned: false, createdAt: Date.now() },
      { id: 'alpha-15', front: 'O', back: 'O is for Orange 🍊', learned: false, createdAt: Date.now() },
      { id: 'alpha-16', front: 'P', back: 'P is for Pizza 🍕', learned: false, createdAt: Date.now() },
      { id: 'alpha-17', front: 'Q', back: 'Q is for Queen 👑', learned: false, createdAt: Date.now() },
      { id: 'alpha-18', front: 'R', back: 'R is for Robot 🤖', learned: false, createdAt: Date.now() },
      { id: 'alpha-19', front: 'S', back: 'S is for Sun ☀️', learned: false, createdAt: Date.now() },
      { id: 'alpha-20', front: 'T', back: 'T is for Tree 🌳', learned: false, createdAt: Date.now() },
      { id: 'alpha-21', front: 'U', back: 'U is for Umbrella ☂️', learned: false, createdAt: Date.now() },
      { id: 'alpha-22', front: 'V', back: 'V is for Violin 🎻', learned: false, createdAt: Date.now() },
      { id: 'alpha-23', front: 'W', back: 'W is for Watermelon 🍉', learned: false, createdAt: Date.now() },
      { id: 'alpha-24', front: 'X', back: 'X is for Xylophone 🎵', learned: false, createdAt: Date.now() },
      { id: 'alpha-25', front: 'Y', back: 'Y is for Yo-yo 🪀', learned: false, createdAt: Date.now() },
      { id: 'alpha-26', front: 'Z', back: 'Z is for Zebra 🦓', learned: false, createdAt: Date.now() },
    ],
  },
];
